### ISSUE TITLE
Named subpatterns with the same name

### ISSUE THREAD

**Issue by lucazav** [tdhock/namedCapture#15]
I need to use a named group multiple time ina regex.
When I try to match the pattern, I get the following error:

> PCRE pattern compilation error
> 	'two named subpatterns have the same name (PCRE2_DUPNAMES not set)'

Here a way to reproduce the error:

```
library(namedCapture)

s <- "foo bar"
rx <- r"{(?P<n>foo)|(?P<n>bar)}"

str_match_named( s, pattern = rx )
```
How can I set the PCRE2_DUPNAMES flag?

**Comment by lucazav** [comment]
I solved prefixing `(?J)` to my regex. The only problem is that in my case I used the same named group in different positions into alternatives. So the output contains as many columns (named as "<column-name>.<index>") as the times the named group is used:

![image](https://user-images.githubusercontent.com/6104437/111637420-b0ef2080-87f9-11eb-896a-90d7dffb5751.png)

So I was forced to use the `coalesce` function of `dplyr` to merge multiple columns with similar names into one:

```
df %>%
  mutate( across(where(is.character), ~na_if(., "")) ) %>% 
  mutate(
    RefundAmountMerged = coalesce(!!! select(., matches(r"{RefundAmount}"))),
    RefundDateMerged = coalesce(!!! select(., matches("RefundDate"))),
    RefundReasonMerged = coalesce(!!! select(., matches("RefundReason")))
  )
```
It'd be really useful if the output will automatically manage this case.

**Comment by tdhock** [comment]
hi thanks for your interest. I don't really understand your use case -- are you sure you don't want to use str_match_all_named instead? (to get multiple rows instead of multiple columns with the same name??) why do you need output with duplicate column names -- isn't that super confusing?

**Comment by lucazav** [comment]
Hi Toby,

thank you for your interest. Maybe I'm using the wrong function. Here my case. I have an Excel like this one:

![image](https://user-images.githubusercontent.com/6104437/111751180-74243780-8894-11eb-94bd-2ee3d7be6066.png)

I'd like to capture the main entities contained into the notes. They are: _amount_, _date_ and _reason_. The way I do that is using a regex structured as follows:

![image](https://user-images.githubusercontent.com/6104437/111751498-e1d06380-8894-11eb-8a0e-041d1df88d79.png)

where `{entity}` is a placeholder that contains a subregex. As you can see I use the same placeholder in different positions in all the alternatives. That's why I'm getting the result shown in the previous comment.

Is there a best way to get a result like the following one?

![image](https://user-images.githubusercontent.com/6104437/111751885-4c819f00-8895-11eb-8547-db1f2e842e0e.png)

**Comment by tdhock** [comment]
hi thanks for clarifying. what you are doing makes sense. you want to match using one of the 4 alternatives, each of which have the same 4 capture group names (amount, date, reason, currency). intuitively you would like there to be 4 output columns but you get 16 right? I think this is a limitation of the regex engines, which may allow duplicated names but always assigns a unique ID to each capture group. last time I did something like this I gave each group a unique name (?<alternative1_amount>...)(?<alternative2_amount>...)etc and then did post-processing of the results (amount = ifelse(alternative1_amount=="", alternative2_amount, alternative1_amount)). so that is another work-around for now, but you are right that is a total hassle for the user, and the package/function could do that for the user one day if I get time to implement that.
the only issue I can think of is that there is usually an informative error message when the user provides two capture groups which have the same name. we could relax that and stop with an error if there is at least one row with data in two identically named groups (which would not be the case for your pattern where all of the identically named groups are in different alternatives).

**Comment by lucazav** [comment]
Hi Toby,

that's exactly what it is. If your package will manage also this scenario raising an error in case of data in two identically named group in the same row, it'd be a great time saver for the user.

Thank you.

**Comment by tdhock** [comment]
Hi I have implemented a fix for this in my nc package, which is a newer/better version of namedCapture. You can install/try the new software via:
```r
remotes::install_github(c("Rdatatable/data.table@melt-custom-variable", "tdhock/nc@duplicate-names"))
#> Skipping install of 'data.table' from a github remote, the SHA1 (870bd835) has not changed since last install.
#>   Use `force = TRUE` to force installation
#> Skipping install of 'nc' from a github remote, the SHA1 (ebf4b44d) has not changed since last install.
#>   Use `force = TRUE` to force installation
subject.vec <- c(
  "EUR 5.00 Theft in delivery inserted in wire transfer 11/02/2021",
  "EUR 50.00 - Refund for theft in delivery - 30/07/2020",
  "EUR68.50 - Refund for theft in delivery 02/07/2020",
  "45.00 EUR 29/10/2020 Refund for theft in delivery",
  "53.00\u20ac Refund for theft in delivery 24/09/2020")
pattern.list <- list(
  list(currency="EUR|\u20ac"),
  list(amount="[0-9.]+", as.numeric),
  list(reason="[A-Za-z ]+?"),
  list(date="[0-9]{2}/[0-9]{2}/[0-9]{4}"))
names(pattern.list) <- sapply(pattern.list, function(L)names(L)[[1]])
sep <- list(" - | |")
pattern <- function(...){
  pats <- list(...)
  sep.pats <- lapply(seq_along(pats), function(i){
    p <- pats[[i]]
    if(i==1)list(p) else list(sep, p)
  })
  list("^", sep.pats, "$")
}
alt.one <- with(pattern.list, pattern(
  currency, amount, reason, date))
nc::capture_first_vec(subject.vec, alt.one, nomatch.error=FALSE)
#>    currency amount                                      reason       date
#> 1:      EUR    5.0 Theft in delivery inserted in wire transfer 11/02/2021
#> 2:      EUR   50.0                Refund for theft in delivery 30/07/2020
#> 3:      EUR   68.5                Refund for theft in delivery 02/07/2020
#> 4:     <NA>     NA                                        <NA>       <NA>
#> 5:     <NA>     NA                                        <NA>       <NA>
alt.list <- with(pattern.list, nc::alternatives(
  pattern(currency, amount, reason, date),
  pattern(amount, currency, date, reason),
  pattern(amount, currency, reason, date)))
nc::capture_first_vec(subject.vec, alt.list)
#>    currency amount                                      reason       date
#> 1:      EUR    5.0 Theft in delivery inserted in wire transfer 11/02/2021
#> 2:      EUR   50.0                Refund for theft in delivery 30/07/2020
#> 3:      EUR   68.5                Refund for theft in delivery 02/07/2020
#> 4:      EUR   45.0                Refund for theft in delivery 29/10/2020
#> 5:        €   53.0                Refund for theft in delivery 24/09/2020
```

**Comment by tdhock** [comment]
here is a simplified version, using another new function (altlist)
```r
remotes::install_github(c("Rdatatable/data.table@melt-custom-variable", "tdhock/nc@duplicate-names"))
#> Skipping install of 'data.table' from a github remote, the SHA1 (870bd835) has not changed since last install.
#>   Use `force = TRUE` to force installation
#> Skipping install of 'nc' from a github remote, the SHA1 (3e5c413f) has not changed since last install.
#>   Use `force = TRUE` to force installation
subject.vec <- c(
  "EUR 5.00 Theft in delivery inserted in wire transfer 11/02/2021",
  "EUR 50.00 - Refund for theft in delivery - 30/07/2020",
  "EUR68.50 - Refund for theft in delivery 02/07/2020",
  "45.00 EUR 29/10/2020 Refund for theft in delivery",
  "53.00\u20ac Refund for theft in delivery 24/09/2020")
pat.list <- nc::altlist(
  currency="EUR|\u20ac",
  amount=list("[0-9.]+", as.numeric),
  reason="[A-Za-z ]+?",
  date=list(
    "[0-9]{2}/[0-9]{2}/[0-9]{4}",
    function(d)data.table::as.IDate(d, format="%d/%m/%Y")))
sep <- function(...){
  pats <- list(...)
  sep.pats <- lapply(seq_along(pats), function(i){
    p <- pats[[i]]
    if(i==1)list(p) else list(list(" - | |"), p)
  })
  list("^", sep.pats, "$")
}
pattern <- with(pat.list, nc::alternatives(
  sep(currency, amount, reason, date),
  sep(amount, currency, date, reason),
  sep(amount, currency, reason, date)))
match.dt <- nc::capture_first_vec(subject.vec, pattern)
print(match.dt, class=TRUE)
#>    currency amount                                      reason       date
#>      <char>  <num>                                      <char>     <IDat>
#> 1:      EUR    5.0 Theft in delivery inserted in wire transfer 2021-02-11
#> 2:      EUR   50.0                Refund for theft in delivery 2020-07-30
#> 3:      EUR   68.5                Refund for theft in delivery 2020-07-02
#> 4:      EUR   45.0                Refund for theft in delivery 2020-10-29
#> 5:        €   53.0                Refund for theft in delivery 2020-09-24
```

**Comment by tdhock** [comment]
hi again I created a new function `alternatives_with_shared_groups` which makes this this use case even simpler (see code below). these new features are still not on CRAN though (waiting for data.table to publish new version first).
```r
remotes::install_github(c("Rdatatable/data.table", "tdhock/nc@suggest-re2"))
#> Skipping install of 'data.table' from a github remote, the SHA1 (96860f2d) has not changed since last install.
#>   Use `force = TRUE` to force installation
#> Skipping install of 'nc' from a github remote, the SHA1 (bebfc3df) has not changed since last install.
#>   Use `force = TRUE` to force installation
subject.vec <- c(
  "EUR 5.00 Theft in delivery inserted in wire transfer 11/02/2021",
  "EUR 50.00 - Refund for theft in delivery - 30/07/2020",
  "EUR68.50 - Refund for theft in delivery 02/07/2020",
  "45.00 EUR 29/10/2020 Refund for theft in delivery",
  "53.00\u20ac Refund for theft in delivery 24/09/2020")
sep <- function(x, y, ...){
  if(missing(y)){
    list("^", x, "$")
  }else{
    sep(list(x, list(" - | |"), y), ...)
  }
}
pattern <- nc::alternatives_with_shared_groups(
  currency="EUR|\u20ac",
  amount=list("[0-9.]+", as.numeric),
  reason="[A-Za-z ]+?",
  date=list(
    "[0-9]{2}/[0-9]{2}/[0-9]{4}",
    function(d)data.table::as.IDate(d, format="%d/%m/%Y")),
  sep(currency, amount, reason, date),
  sep(amount, currency, date, reason),
  sep(amount, currency, reason, date))
match.dt <- nc::capture_first_vec(subject.vec, pattern)
print(match.dt, class=TRUE)
#>    currency amount                                      reason       date
#>      <char>  <num>                                      <char>     <IDat>
#> 1:      EUR    5.0 Theft in delivery inserted in wire transfer 2021-02-11
#> 2:      EUR   50.0                Refund for theft in delivery 2020-07-30
#> 3:      EUR   68.5                Refund for theft in delivery 2020-07-02
#> 4:      EUR   45.0                Refund for theft in delivery 2020-10-29
#> 5:        \200   53.0                Refund for theft in delivery 2020-09-24
```
